### ISSUE TITLE
The firmware was successfully flashed, but there are issues with the display.

### ISSUE THREAD

**Issue by zhenchuanpeng** [NaitikSanas/MicroCanvas#6]
I don't know why my LCD screen shows a white screen after successfully burning the firmware. I have no idea where to start troubleshooting this issue; please help me.
![image](https://github.com/user-attachments/assets/82639297-f145-488a-8b4b-b96d6b8a096c)
[Kconfig.projbuild.txt](https://github.com/user-attachments/files/18137198/Kconfig.projbuild.txt)

device:ESP32S3-WROOM-1-N16R8、ST7789 -2.4

**Comment by zhenchuanpeng** [comment]
![img_v3_02hj_e0b57fc1-4f15-4800-9398-6bea7530554g](https://github.com/user-attachments/assets/c115a81e-6c93-40a6-b1cf-0088dec29ba6)

**Comment by NaitikSanas** [comment]
Hi, Can you tell me from Main.c which App demo is it running? Second thing for ST7789 configuration i recommend you turn on "Enable Frame Buffer" for Smooth Rendering. 
Replace everything in main.c With Following snippet, This should draw a Orange rectangle. Let me know it it works or not. 

```
#include "main.h"
#include "app.h"


void app_main(){
    start_uCanvas_engine();
    uCanvas_Scene_t* scene_1 = New_uCanvas_Scene();
    uCanvas_set_active_scene(scene_1);
    uCanvas_universal_obj_t* rect = New_uCanvas_2DRectangle(20,20,50,50);
    rect->properties.fill = FILL;
    uCanvas_Set_Color(rect,255,150,0);

}
```

**Comment by NaitikSanas** [comment]
I noticed I hardcoded the display resolution in display port file. I have fixed it on main branch, so now it should take resolution from configuration file. @zhenchuanpeng let me know if you face any issues :) 

![image](https://github.com/user-attachments/assets/54ea2c63-c071-4ff0-850b-e953088ad9ce)

**Comment by zhenchuanpeng** [comment]
Hey buddy, I can't find the 33rd pin of the ESP32S3. I'm not sure if this is the reason. Besides, after replacing the code in the “main\main.c” file under this path and burning it in, there's still no effect.

**Comment by zhenchuanpeng** [comment]
I'll give it another try, including updating your code locally. Thanks for your explanation.

**Comment by NaitikSanas** [comment]
> I can't find the 33pin of the ESP32S3
Configure it to pin that is available on your board. you can use any GPIO for connection display.

**Comment by zhenchuanpeng** [comment]
Sure,I've already set it to 39pin :)

**Comment by zhenchuanpeng** [comment]
![image](https://github.com/user-attachments/assets/3e619dde-640f-4e9b-8400-a21f1942a8c7)

**Comment by NaitikSanas** [comment]
@zhenchuanpeng  whats the issue in previous image? have you managed to resolve it?

**Comment by zhenchuanpeng** [comment]
Hey, buddy! The problem has been solved. I've made some adjustments to the configuration. Let me show you the effect. Kudos!
![img_v3_02hj_39192992-4340-4a39-8ee4-b80bf9728edg](https://github.com/user-attachments/assets/4ab8aa3d-e0d9-4e39-acd2-76b1322ae773)
I'll study carefully how to operate it:)

**Comment by zhenchuanpeng** [comment]
> @zhenchuanpeng whats the issue in previous image? have you managed to resolve it?

Hey, buddy! The problem has been solved. I've made some adjustments to the configuration. Let me show you the effect. Kudos!
img_v3_02hj_39192992-4340-4a39-8ee4-b80bf9728edg
I'll study carefully how to operate it:)

**Comment by NaitikSanas** [comment]
That's great! I see the colors are inverted for some reason. It should have looked like this :
![20241215_122400](https://github.com/user-attachments/assets/529e2d5c-7720-421d-baeb-6962127fbede)

**Comment by NaitikSanas** [comment]
@zhenchuanpeng Since this project is in development stage, especially with ST7789 Support there will be some bugs, unexpected behaviors and limitations. Feel free to report issues you encounter. Thank you for your interest in this project :D

**Comment by NaitikSanas** [comment]
@zhenchuanpeng Hi, another thing to note,  I have recently added support for Fonts, initially there was fixed font type of 10px size. you can now change font type property in your code from available selection of fonts. I recommend you use fetch current version of code. There is demo for how to use fonts as well :)

**Comment by zhenchuanpeng** [comment]
> @zhenchuanpeng Hi, another thing to note, I have recently added support for Fonts, initially there was fixed font type of 10px size. you can now change font type property in your code from available selection of fonts. I recommend you use fetch current version of code. There is demo for how to use fonts as well :)

Of course, buddy. I'll handle the repo management based on your last update. Meanwhile, I've noticed some issues while running the repo, and I will provide you with feedback and some suggestions for improvement. I'll get back to you once I'm home.

**Comment by NaitikSanas** [comment]
> I've noticed some issues while running the repo,

Alright Sure! Feel free to create new issues so we can keep things on track. I'll close this issue as of now :)
